version: "3.8"
services:
  postgres-db:
    container_name: fortuna-postgres
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fortuna_dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
